doctor/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('doctor/<slug:doctor_slug>/', views.DoctorDetailView.as_view(), name='doctor_detail'),
    path('add-doctor/', views.DoctorAddView.as_view(), name='doctor_add'),
    path('edit/<slug:edit_slug>/', views.DoctorUpdateView.as_view(), name='doctor_edit'),
    path('specialty/<slug:specialty_slug>', views.DoctorsBySpecialty.as_view(), name='doctors_by_specialty'),
    path('delete-appointment/<int:pk>/', views.appointment_delete, name='appointment_delete')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('doctor.urls')),
    path('users/', include('users.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 


if settings.DEBUG: 
    urlpatterns += debug_toolbar_urls()

users/urls.py
from django.urls import path, reverse_lazy

from .views import LoginUser, ProfileUser, RegisterUser, UserPasswordChangeView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .forms import UserPasswordResetForm, UserSetPasswordFrom

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name = 'users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name = 'users/password_reset_form.html',
        form_class = UserPasswordResetForm,
        email_template_name = 'users/password_reset_email.html',
        success_url = reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name = 'users/password_reset_confirm.html',
        form_class = UserSetPasswordFrom,
        success_url = reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name = 'users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('profile/<int:pk>/', ProfileUser.as_view(), name='profile'),
    # path('profile/edit/<slug:edit_profile>/', ProfileUser.as_view(), name='profile_edit'),
]

doctor/models.py
from django.db import models
from django.contrib.auth import get_user_model
import random

from django.urls import reverse


WEEKDAYS = (
    (1, "Monday"),
    (2, "Tuesday"),
    (3, "Wednesday"),
    (4, "Thursday"),
    (5, "Friday"),
    (6, "Saturday"),
    (7, "Sunday"),
)


# Number of doctor
def number_of_doctor():
    return random.randint(100000, 999999)


class Doctor(models.Model):
    image = models.ImageField(upload_to='doctor_images', blank=True)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    number = models.PositiveIntegerField(unique=True, default=number_of_doctor)
    slug = models.SlugField(max_length=255, db_index=True, blank=True)
    age = models.PositiveIntegerField()
    description = models.TextField()
    experience = models.PositiveIntegerField()
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    specialty = models.ForeignKey('Specialty', on_delete=models.CASCADE, related_name='doctors')
    owner = models.OneToOneField(get_user_model(), null=True, blank=True, on_delete=models.CASCADE, related_name='doctor', limit_choices_to={'groups__name': 'Doctors'})


    def __str__(self):
        return self.name + ' ' + self.surname


    def get_absolute_url(self):
        return reverse('doctor_detail', kwargs={'doctor_slug': self.slug,})


    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctors'


class Specialty(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    

    def __str__(self):
        return self.name
    

    def get_absolute_url(self):
        return reverse('doctors_by_specialty', kwargs={'specialty_slug': self.slug})
    

    class Meta:
        verbose_name = 'Specialty'
        verbose_name_plural = 'specialties'


class DoctorFeedback(models.Model):
    description = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    star = models.FloatField(default=0)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='comments')
    from_user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments_to')


    def __str__(self):
        return f'{self.doctor.name} -- {self.star}'
    
    
    class Meta:
        ordering = ['-time_create']


class Notification(models.Model):
    is_read = models.BooleanField(default=False)
    message = models.TextField()
    time_create = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='notification')


    def get_absolute_url(self):
        return reverse('doctor_detail', kwargs={'doctor_slug': self.user.doctor.slug})
    

class Appointment(models.Model):
    appointment_date = models.DateTimeField()
    create_date = models.DateTimeField(auto_now_add=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctor_appointments')
    patient = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='user_appointments')

    
    def __str__(self):
        return f'Doctor {self.doctor.name} - {self.appointment_date.strftime('%Y/%m/%d - %H:%M')} - {self.patient.username}'
    
    
    class Meta:
        ordering = ['appointment_date']


class WorkingHours(models.Model):
    doctor = models.ForeignKey('Doctor', on_delete=models.CASCADE, related_name='work_hours')
    weekday = models.IntegerField(choices=WEEKDAYS, unique=True)
    from_time = models.TimeField()
    to_time = models.TimeField()


    def __str__(self):
        return f'{self.doctor} -- {self.weekday} day of the week -- from {self.from_time} to {self.to_time}'

    
    class Meta:
        verbose_name = 'Working hour'
        verbose_name_plural = 'Working hours'

doctor/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Doctor, Specialty, DoctorFeedback, Appointment
from project.settings import DATETIME_INPUT_FORMATS


class DoctorAddFrom(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput)
    specialty = forms.ModelChoiceField(queryset=Specialty.objects.all(), empty_label='Specialty not selected')
    

    class Meta:
        model = Doctor
        exclude = ['slug', 'number', 'owner']


    def __init__(self, *args, **kwargs):
        super(DoctorAddFrom, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs.update({'class': 'w-full rounded', 'placeholder': f'{f.capitalize()}'})


    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) < 50:
            raise ValidationError('Description must contain more than 50 characters.')
        return description
    
    
class CommentAddFrom(forms.ModelForm):

    
    class Meta:
        model = DoctorFeedback
        fields = ['description', 'star']


    def __init__(self, *args, **kwargs):
        super(CommentAddFrom, self).__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({'class': 'w-full rounded-xl', 'placeholder': 'Description...', 'rows': '3'})


class DateForm(forms.ModelForm):
    appointment_date = forms.DateTimeField(input_formats=DATETIME_INPUT_FORMATS, widget=forms.DateTimeInput(format=DATETIME_INPUT_FORMATS))


    class Meta:
        model = Appointment
        fields = ['appointment_date']

    def __init__(self, *args, **kwargs):
        super(DateForm, self).__init__(*args, **kwargs)
        self.fields['appointment_date'].widget.attrs.update({'placeholder': 'Select date...'})

doctor/views.py
from django.db.models.base import Model as Model
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.views.generic.edit import FormMixin
from django.shortcuts import get_object_or_404, redirect, render
from .models import Doctor, number_of_doctor, Notification, Appointment
from .forms import DoctorAddFrom, CommentAddFrom, DateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from .decorators import only_for_doctors
import json
import pandas as pd 

from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Prefetch

from .red_cch import get_data

class MainView(ListView):
    model = Doctor
    template_name = 'doctor/main.html'
    context_object_name = 'doctors'
    

    def get_queryset(self):
        doctors = Doctor.objects.prefetch_related('specialty').filter()
        return get_data(doctors)
    

class DoctorDetailView(DetailView, FormMixin):
    model = Doctor
    template_name = 'doctor/doctor_detail.html'
    slug_url_kwarg = 'doctor_slug'
    context_object_name = 'doctor'
    form_class = CommentAddFrom
    second_form_class = DateForm

    def get_object(self):
        return Doctor.objects.prefetch_related('comments__from_user').get(slug=self.kwargs[self.slug_url_kwarg])
    

    def get_success_url(self):
        return reverse('doctor_detail', kwargs={'doctor_slug': self.kwargs[self.slug_url_kwarg]})
    

    def get_context_data(self, **kwargs):
        context = super(DoctorDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class()
        context['time_list'] = self.get_object().work_hours.all
        for i in self.get_object().work_hours.all():
            context[f'weekday{i.weekday}'] = json.dumps(self.list_of_working_hours(i.from_time.strftime('%H:%M'), i.to_time.strftime('%H:%M')))
        return context
    

    #create list of workng hours for a doctor (This is need for datetimepicker appointments)
    @staticmethod
    def list_of_working_hours(from_time, to_time):
        result = pd.date_range(from_time, to_time, freq='60min').strftime('%H:%M')
        # for time in range(from_time.hour, to_time.hour + 1):
        #     result.append(datetime.time(time, from_time.minute).strftime('%H:%M'))
        return list(result)


    def form_invalid(self, **kwargs):
        return self.render_to_response(self.get_context_data(**kwargs))
    

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if 'form' in request.POST:
            form_class = self.form_class(request.POST)
            if form_class.is_valid():
                f = form_class.save(commit=False)
                f.doctor = self.object
                f.from_user = self.request.user
                f.save()
                Notification.objects.create(user=self.object.owner, message=f'{self.request.user} left a comment for your doctor.') 
                return redirect('doctor_detail', self.kwargs[self.slug_url_kwarg])
            else:
                return self.form_invalid(form_class)
        else:
            form_class = self.second_form_class(request.POST)
            if form_class.is_valid():
                f = form_class.save(commit=False)
                f.doctor = self.object
                f.patient = request.user
                f.save()
                return redirect('users:profile', request.user.id)
            else:
                return self.form_invalid(form_class)

@method_decorator(only_for_doctors('Doctors'), 'dispatch')
class DoctorAddView(LoginRequiredMixin, CreateView):
    model = Doctor
    excludes = ['slug']
    form_class = DoctorAddFrom
    template_name = 'doctor/doctor_add.html'
    success_url = reverse_lazy('main')


    def form_valid(self, form):
        f = form.save(commit=False)
        f.slug = f'{f.name.lower()}-{f.surname.lower()}-{f.number}'
        f.number = number_of_doctor()
        f.owner = self.request.user
        f.save()
        return super().form_valid(form)
        
    
@method_decorator(only_for_doctors('Doctors'), 'dispatch')
class DoctorUpdateView(LoginRequiredMixin, UpdateView):
    model = Doctor
    template_name = 'doctor/doctor_edit.html'
    form_class = DoctorAddFrom
    slug_url_kwarg = 'edit_slug'
    success_url = reverse_lazy('main')


    def form_valid(self, form):
        f = form.save(commit=False)
        f.slug = f'{f.name.lower()}-{f.surname.lower()}-{f.number}'
        f.save()
        return super().form_valid(form)


class DoctorsBySpecialty(ListView):
    model = Doctor
    template_name = 'doctor/main.html'
    context_object_name = 'doctors'


    def get_queryset(self):
        doctors =  Doctor.objects.prefetch_related('specialty').filter(specialty__slug=self.kwargs['specialty_slug'])
        return doctors
    
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def appointment_delete(request, pk):
    Appointment.objects.filter(pk=pk).delete()
    return render(request, 'doctor/partials/appointment_list.html', {'profile': request.user})

doctor/templates/doctor/doctor_add.html
{% extends 'base.html' %}

{% block title %}Add Doctor{% endblock %}

{% block content %}
<div class="w-full mx-auto px-14 py-14 flex justify-between items-center">
    <div class="w-1/2">
        <form action="" method="POST" enctype="multipart/form-data" class="first:-mt-4">
            {% csrf_token %}
            <div class="text-red-600">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <div class="mt-4">
                {{f}}
            </div>
            <div class="text-red-600">{{ f.errors }}</div>
            {% endfor %}
            <button type="submit" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Add</button>
        </form>
    </div>
    <div class="w-1/2 text-center">
        <h1 class="text-7xl">Add Doctor</h1>
    </div>
</div>
{% endblock %}

doctor/templates/doctor/doctor_detail.html
{% extends 'base.html' %}

{% block title %}{{ doctor.name }} {{ doctor.surname }}{% endblock %}

{% block content %}
<div class="max-w-screen-xl mx-auto p-4">
    {% include 'doctor/partials/link_back.html' %}
    <div class="flex my-20 space-x-10">
        <div class="w-1/3">
            <img class="w-[100px] h-[100px] object-cover object-top rounded-full border border-gray-700" src="{{ doctor.image.url }}" alt="">
            <h1 class="text-2xl">{{ doctor.name  }} {{ doctor.surname  }}</h1>
            <p class="text-md">{{ doctor.specialty  }}</p>
            <p class="mt-10">{{ doctor.description|truncatewords:30|slice:-2  }} <button onclick="show_descrip()" class="text-blue-500">More...</button></p>       
            <div onclick="close_descrip()" id="descrip" class="fixed top-0 left-0 bg-black bg-opacity-50 w-screen h-screen hidden justify-center opacity-0 items-center transition-opacity duration-500">
                <div onclick="event.stopImmediatePropagation()" class="relative bg-white w-[40%] p-4 rounded-xl">
                    <h1 class="text-center font-bold">Doctor's description</h1>
                    <p class="mt-2">{{ doctor.description }}</p>
                    <button onclick="close_descrip()" class="absolute right-2 top-2">                    
                        <svg width="10px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                            <path d="M376.6 84.5c11.3-13.6 9.5-33.8-4.1-45.1s-33.8-9.5-45.1 4.1L192 206 56.6 43.5C45.3 29.9 25.1 28.1 11.5 39.4S-3.9 70.9 7.4 84.5L150.3 256 7.4 427.5c-11.3 13.6-9.5 33.8 4.1 45.1s33.8 9.5 45.1-4.1L192 306 327.4 468.5c11.3 13.6 31.5 15.4 45.1 4.1s15.4-31.5 4.1-45.1L233.7 256 376.6 84.5z"/>
                        </svg>
                    </button>
                </div>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form2.appointment_date }}
                <!-- for all users who is doctor or partient -->
                {% if request.user.is_authenticated and request.user != doctor.owner %} 
                <button type="submit" name="form2" class="mt-10 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Appointment</button>
                {% else %}
                <a href="{% url 'users:login' %}" class="mt-10 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Appointment</a>
                {% endif %}
            </form> 
        </div>
        <div class="bg-gray-100 rounded-xl text-center w-2/3 px-4 pb-4">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="mt-4 w-full flex space-x-5 items-center justify-end">
                    <div><p>Select rating: </p></div>
                    <div>
                        <label class="label" for="star-1">
                            <i class="fa fa-star" aria-hidden="true"></i>
                        </label>
                        <input class="input hidden" type="radio" id="star-1" name="star" value="1">
                        <label class="label" for="star-2">
                            <i class="fa fa-star"></i>
                        </label>
                        <input class="input hidden" type="radio" id="star-2" name="star" value="2">
                        <label class="label" for="star-3">
                            <i class="fa fa-star"></i>
                        </label>
                        <input class="input hidden" type="radio" id="star-3" name="star" value="3">
                        <label class="label" for="star-4">
                            <i class="fa fa-star"></i>
                        </label>
                        <input class="input hidden" type="radio" id="star-4" name="star" value="4">
                        <label class="label" for="star-5">
                            <i class="fa fa-star"></i>
                        </label>
                        <input class="input hidden" type="radio" id="star-5" name="star" value="5" checked>
                    </div>
                </div>
                <div class="text-red-600">{{ form.non_field_errors }}</div>
                <div>{{ form.errors }}</div>
                <div class="mt-4 w-full">
                    {{ form.description }}
                </div>
                <div class="text-red-600">{{ form.description.errors }}</div>
                {% if doctor.owner == request.user %}
                <button type="submit" disabled class="group relative hover::after:content-[attr(data-title)] w-full mt-5 text-white rounded-lg disabled:bg-gray-300 py-2 px-4">Comment
                    <p class="absolute bg-gray-500 p-2 rounded-lg text-white hidden group-hover:block right-0 bottom-11">You can't add comments to your doctor! <span class="before:content-['▾'] absolute top-7 right-1/2"></span></p>
                </button>
                {% else %}
                <button type="submit" name="form" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Comment</button>
                {% endif %}
            </form>
            <hr class="mt-5 border-black">
            <div id="comment_list">
                {% include 'doctor/partials/comment_list.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    let currentDate = new Date()
    let minimalDate = currentDate.setDate(currentDate.getDate() + 1)

    let logic = function( currentDateTime ){
        if(currentDateTime.getDay()==1){
            this.setOptions({
                allowTimes: JSON.parse('{{ weekday1|escapejs }}')
            })
        } else if (currentDateTime.getDay()==2){
            this.setOptions({
                allowTimes: JSON.parse('{{ weekday2|escapejs }}')
            })
        } else if (currentDateTime.getDay()==3){
            this.setOptions({
                allowTimes: JSON.parse('{{ weekday3|escapejs }}')
            })
        } else if (currentDateTime.getDay()==4){
            this.setOptions({
                allowTimes: JSON.parse('{{ weekday4|escapejs }}')
            })
        } else if (currentDateTime.getDay()==5){
            this.setOptions({
                allowTimes: JSON.parse('{{ weekday5|escapejs }}')
            })
        }
    };

    $(function () {
        $("#id_appointment_date").datetimepicker({
            minDate: minimalDate,
            onGenerate:function( ct ){
                jQuery(this).find('.xdsoft_date.xdsoft_weekend')
                .addClass('xdsoft_disabled');
            },
            onChangeDateTime: logic,
            onShow: logic
        });
    });

    
    function show_descrip(){
        descrip = document.getElementById('descrip')
        descrip.classList.remove('hidden')
        descrip.classList.add('flex')
        setTimeout(() => {
            descrip.classList.add('opacity-100')
        }, 20)
    }


    function close_descrip(){
        descrip = document.getElementById('descrip')
        descrip.classList.add('opacity-0')
        descrip.classList.remove('opacity-100')
        setTimeout(() => {
            descrip.classList.add('hidden')
            descrip.classList.remove('flex')
        },500)
    }
</script>
{% endblock %}

doctor/templates/doctor/doctor_edit.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="w-full mx-auto px-14 py-14 flex justify-between items-center">
    <div class="w-1/2">
        <form action="" method="POST" enctype="multipart/form-data" class="first:-mt-4">
            {% csrf_token %}
            {% for f in form %}
            <div class="mt-4">
                {{ f }}
            </div>
            {% endfor %}
            <button type="submit" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Edit</button>
        </form>
    </div>
    <div class="w-1/2 text-center">
        <h1 class="text-7xl">Edit Doctor</h1>
    </div>
</div>
{% endblock %}

doctor/templates/doctor/list_specialty.html
<div class="max-w-screen-xl m-auto flex pt-5">
    <a href="{% url 'main' %}" class="bg-gray-700 text-white p-1 rounded-lg justify-start mr-5 last:mr-0">All</a>
    {% for specialty in specialties %}
    <a href="{{ specialty.get_absolute_url }}" class="bg-gray-700 text-white p-1 rounded-lg justify-start mr-5 last:mr-0">{{ specialty.name }}</a>
    {% endfor %}
</div>

doctor/templates/doctor/main.html
{% extends 'base.html' %}
{% load doctortags %}
{% load usertags %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    {% list_specialty %} 
    {% for doctor in doctors %}
    <div class="max-w-screen-xl h-60 mx-auto my-12 flex rounded-md bg-gray-700 border-4 border-gray-700">
        <div class="w-1/4 bg-gray-500 overflow-hidden rounded-sm">
            <a href="{{ doctor.get_absolute_url }}">
                <img src="{{ doctor.image.url }}" alt="{{ doctor.name }} {{ doctor.surname }}">
            </a>
        </div>
        <div class="w-3/4 p-8 text-white relative">
            <div class="text-end">
                <a href="{{ doctor.specialty.get_absolute_url }}" class="underline underline-offset-4">Specialty: {{ doctor.specialty }}</a>
            </div>
            <div>
                <p>Name: <span class="text-2xl font-bold">{{ doctor.name }} {{ doctor.surname }}</span></p>
                <p>Specialty: {{ doctor.specialty }}</p>
                <p>Experiense: {{ doctor.experience }} years</p>
                <p>About: {{ doctor.description|truncatewords:25 }}</p>
                {% if user|has_group:'Doctor' and user.doctor.slug == doctor.slug %}
                <p class="mt-3"><a href="{% url 'doctor_edit' user.doctor.slug %}" class="underline text-yellow-600">Edit</a></p>
                {% endif %}
            </div>
            <hr class="w-48 h-1 mx-auto border-0 rounded bg-white absolute bottom-2 left-[calc(50%-6rem)]">
        </div>
    </div>
    {% endfor %}
{% endblock %}