project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('doctor.urls')),
    path('users/', include('users.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 


if settings.DEBUG: 
    urlpatterns += debug_toolbar_urls()

users/urls.py
from django.urls import path, reverse_lazy

from .views import LoginUser, ProfileUser, RegisterUser, UserPasswordChangeView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .forms import UserPasswordResetForm, UserSetPasswordFrom

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name = 'users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name = 'users/password_reset_form.html',
        form_class = UserPasswordResetForm,
        email_template_name = 'users/password_reset_email.html',
        success_url = reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name = 'users/password_reset_confirm.html',
        form_class = UserSetPasswordFrom,
        success_url = reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name = 'users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('profile/<int:pk>/', ProfileUser.as_view(), name='profile'),
    # path('profile/edit/<slug:edit_profile>/', ProfileUser.as_view(), name='profile_edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    photo = models.ImageField(verbose_name='Image', upload_to='user_images', null=True, blank=True, default='user_default.png')

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import get_user_model


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Login', widget=forms.TextInput())
    password = forms.CharField(label='Password', widget=forms.PasswordInput())


    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs.update({'class': 'w-full rounded', 'placeholder': f'{self.fields[f].label}'})


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Login')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput())
    as_doctor = forms.CharField(label='As Doctor', widget=forms.CheckboxInput(), required=False)
    usable_password = None
   

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'as_doctor']
        excludes = ['usable_password']
        labels = {
            'email': 'Email',
            'first_name': 'Name',
            'last_name': 'Surname'
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs.update({'class': 'w-full rounded', 'placeholder': f'{self.fields[f].label}'})
        self.fields['as_doctor'].widget.attrs.update({'class': 'rounded'})


    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email):
            raise forms.ValidationError('The Email already exists')
        return email
    

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput())
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Repeat new password', widget=forms.PasswordInput())


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields:
             self.fields[f].widget.attrs.update({'class': 'w-full rounded', 'placeholder': f'{self.fields[f].label}'})


class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs.update({'class': 'w-full rounded', 'placeholder': f'{self.fields[f].label}'})


class UserSetPasswordFrom(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs.update({'class': 'w-full rounded', 'placeholder': f'{self.fields[f].label}'})

users/views.py
from django.db.models.base import Model as Model
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordChangeView
from .forms import LoginForm, RegisterForm, UserPasswordChangeForm

from django.views.generic import CreateView, DetailView
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404

from doctor.models import Appointment
import datetime

from .models import User


class LoginUser(LoginView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('main')
    title = 'Log In'


class RegisterUser(CreateView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('users:login')


    def form_valid(self, form: RegisterForm):
        f = form.save(commit=False)
        if form.cleaned_data['as_doctor'] == 'True':
            group = Group.objects.get(name='Doctors')
        else:
            group = Group.objects.get(name='Patients')
        f.save()
        f.groups.add(group)
    
        return super().form_valid(form)


class ProfileUser(DetailView):
    template_name = 'users/profile.html'
    context_object_name = 'profile'


    def get_object(self):
        self.appoitments_list(self.request.user)
        return User.objects.get(pk=self.kwargs[self.pk_url_kwarg])
    
    
    # Appointments list only with appointment date < current time, if current time > appointment date --> delete an appointment
    @staticmethod
    def appoitments_list(user):
        user_appointments = Appointment.objects.filter(patient=user)
        for appointment in user_appointments:
            if appointment.appointment_date.date() < datetime.datetime.now().date():
                if appointment.appointment_date.time() < datetime.datetime.now().time():
                    appointment.delete()
        return user_appointments
    

class UserPasswordChangeView(PasswordChangeView):
    template_name = 'users/password_change_form.html'
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
<div class="">


    <div class="w-1/4 mx-auto text-center">
        <h1 class="text-3xl">Log In</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="text-red-600">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <div class="mt-4 w-full">
                {{ f }}
            </div>
            <div class="text-red-600">{{ f.errors }}</div>
            {% endfor %}
            <p class="mt-2">Are you not register? <a href="{% url 'users:register' %}" class="underline">Register</a></p>
            <p class="mt-2">Did you forgot a password? <a href="{% url 'users:password_reset' %}" class="underline">Password confirmation</a></p>
            <button type="submit" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Log In</button>
        </form>
    </div>

</div>


{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %}Password Changed{% endblock %}

{% block content %}
<p>Your password was changed!!</p>


{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %}Change Password{% endblock %}

{% block content %}
<div class="">
    <div class="w-1/4 mx-auto text-center">
        <h1 class="text-3xl">Change password</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="text-red-600">{{ form.non_field_errors }}</div>
            {% for f in form %}
            <div class="mt-4 w-full">
                {{f}}
            </div>
            <div class="text-red-600">{{f.errors}}</div>
            {% endfor %}
            <button type="submit" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Change Password</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="w-1/4 mx-auto text-center">
    <p class="text-3xl">{% translate "Your password has been set.  You may go ahead and log in now." %}</p>
    <p class="mt-4"><a href="{% url 'users:login' %}" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">{% translate 'Log in' %}</a></p>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="w-1/4 mx-auto text-center">
    <h1 class="text-3xl">Create new password</h1>
    <form method="post">
        {% csrf_token %}
        <div class="text-red-600">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <div class="mt-4 w-full">
            {{f}}
        </div>
        <div class="form-text-red-600">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Create password</button>
    </form>
</div>


{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="w-1/4 mx-auto text-center">
    <h1 class="text-3xl">Email confirmation</h1>
    <p class="mt-4">{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
</div>


{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
{% translate "Thanks for using our site!" %}
{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}

<div class="w-1/4 mx-auto text-center">
    <h1 class="text-3xl">Password reset</h1>
    <form method="post">
        {% csrf_token %}
        <div class="text-red-600">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <div class="mt-4 w-full">
            {{ f }}
        </div>
        <div class="text-red-600">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Reset password</button>
    </form>
</div>


{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load usertags %}
{% block title %}Profile{% endblock %}

{% block content %}
<div class="max-w-screen-xl mx-auto p-4">
    {% include 'doctor/partials/link_back.html' %}
    {% if profile.doctor %}
    <h1 class="text-3xl text-center mt-10">User as a Doctor</h1>
    {% else %}
    <h1 class="text-3xl text-center mt-10">User</h1>
    {% endif %}
    <div class="my-12">
        <div class="bg-gray-100 rounded-xl flex items-center justify-between p-4">
            <div class="flex items-center">
                <img width="100px" src="{{ profile.photo.url }}" alt="" class="w-[100px] h-[100px] object-cover object-top rounded-full border border-gray-700">
                <div class="ml-6">
                    <h1 class="text-2xl">{{ profile.get_full_name }} ({{ profile.username }})</h1>
                    <div class="bg-gray-200 inline-block rounded-xl px-2">{{ profile.email }}</div>
                </div>
            </div>
            <div class="space-x-4">
                {% if profile|has_group:'Doctors' and not profile.doctor %}
                <a href="{% url 'doctor_add' %}" class="underline">Add doctor</a>
                {% endif %}
                <a href="{% url 'users:password_change' %}" class="underline">Change password</a>
            </div>
        </div>
    </div>
    <!-- Appointment -->
    {% if profile|has_group:'Patients' %}
    <div id="appointment_list">
        {% include 'doctor/partials/appointment_list.html' %}
    </div>
    {% endif %}
    <!-- Doctor -->
    {% if profile.doctor %}
    <h1 class="text-xl mt-10">User's Doctor</h1>
    <div class="my-3">
        <div class="group bg-gray-100 rounded-xl flex items-center justify-between p-4 hover:bg-gray-700 hover:text-white">
            <div class="flex items-center">
                <img src="{{ profile.doctor.image.url }}" alt="" class="w-[100px] h-[100px] object-cover object-top rounded-full border border-gray-700">
                <div class="ml-6">
                    <h1 class="text-2xl">{{ profile.doctor.name }} {{ profile.doctor.surname }} ({{ profile.doctor.number }}) {{ profile.doctor.age }} y.o.</h1>
                    <p>Experience: {{ profile.doctor.experience }}</p>
                    <div class="bg-gray-200 inline-block rounded-xl px-2 group-hover:bg-gray-600">{{ profile.doctor.specialty }}</div>
                </div>
            </div>
            <div class="space-x-4">
                <a href="{% url 'doctor_detail' profile.doctor.slug %}" class="underline">Detail</a>
                <a href="{% url 'doctor_edit' profile.doctor.slug %}" class="underline">Edit</a>
            </div>
        </div>
    </div>
        {% if profile.doctor.doctor_appointments %}
            <div class="scrollmenu overflow-auto whitespace-nowrap space-x-4">
                {% for appointment in profile.doctor.doctor_appointments.all %}
                    <a href="#" onclick="return false" class="bg-yellow-400 p-4 inline-block rounded-xl">{{ appointment.appointment_date|date:"H:i d M Y" }} - {{ appointment.patient.get_full_name }}</a>
                {% endfor %}
            </div>
        {% endif %}
        {% if profile.notification %}
        <div class=" scrollmenu overflow-auto h-[300px] mt-10">
            <h1 class="text-xl">Notifications</h1>
            {% for n in profile.notification.all %}
            <a href="#" onclick="return false">
                {% if n.is_read %}
                <div class="my-3 p-2 bg-gray-100 rounded-xl flex justify-between">
                {% else %}
                <div class="my-3 p-2 bg-blue-600 text-white rounded-xl flex justify-between">
                {% endif %}
                    <div>{{ n.message }}</div>
                    <div class="text-gray-400">{{ n.time_create|date:'d M Y - H:i' }}</div>
                </div> 
            </a>
            {% endfor %}
        </div>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="">
    <div class="w-1/4 mx-auto text-center">
        <h1 class="text-3xl">Register</h1>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="text-red-600">{{ form.non_field_errors }}</div>
            {% for f in form %}
                {% if not forloop.last %}
                    <div class="mt-4 w-full">
                        {{ f }}
                    </div>
                {% else %}
                    <div class="mt-4">
                        <label for="{{f.id_for_label}}" class="mr-5">{{ f.label }}</label>
                        {{ f }}
                    </div>
                {% endif %}
                <div class="text-red-600">{{ f.errors }}</div>
            {% endfor %}
            <button type="submit" class="w-full mt-5 text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Register</button>
        </form>
    </div>
</div>


{% endblock %}