project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('doctor.urls')),
    path('users/', include('users.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 


if settings.DEBUG: 
    urlpatterns += debug_toolbar_urls()

users/urls.py
from django.urls import path, reverse_lazy

from .views import LoginUser, ProfileUser, RegisterUser, UserPasswordChangeView
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .forms import UserPasswordResetForm, UserSetPasswordFrom

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name = 'users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name = 'users/password_reset_form.html',
        form_class = UserPasswordResetForm,
        email_template_name = 'users/password_reset_email.html',
        success_url = reverse_lazy('users:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'
    ), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name = 'users/password_reset_confirm.html',
        form_class = UserSetPasswordFrom,
        success_url = reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name = 'users/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('profile/<int:pk>/', ProfileUser.as_view(), name='profile'),
    # path('profile/edit/<slug:edit_profile>/', ProfileUser.as_view(), name='profile_edit'),
]

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'doctor/css/style.css' %}">
    {% tailwind_css %}
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="flex flex-col min-h-screen">
    <header>
        <nav class="dark:bg-gray-700 w-full border-gray-600">
            <div class="w-full flex flex-wrap items-center justify-between mx-auto py-4 px-14">
                <a href="{% url 'main' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
                    <img src="{% static  'doctor/images/logo.png' %}" class="h-12" alt="Flowbite Logo">
                    <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">Doctor</span>
                </a>
                <div class="flex md:order-2 items-center space-x-4">
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:profile' user.pk %}" class="text-white">{{ user.username|upper }}</a>
                    <form method="POST" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="text-white bg-red-600 hover:bg-red-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Log Out</button>
                    </form>  
                    {% else %}
                    <a href="{% url 'users:login' %}" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Log In</a>
                    {% endif %}
                </div>
                <!-- <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
                    {% if user.is_authenticated %}
                    <div class="grid grid-cols-2 items-center text-center">
                        <a href="{% url 'users:profile' user.pk %}" class="text-white">{{user.username|upper}}</a>
                        <form method="POST" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="text-white bg-red-600 hover:bg-red-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Log Out</button>
                        </form>
                    </div>   
                    {% else %}
                    <a href="{% url 'users:login' %}" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-4 py-2 text-center">Log In</a>
                    {% endif %}
                </div> -->
                <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
                    <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 bg-gray-700">
                        <li>
                            <a href="{% url 'main' %}" class="block py-2 px-3 text-blue-500" aria-current="page">Doctors</a>
                        </li>
                        <li>
                            <a href="#" class="block py-2 px-3 text-white hover:text-blue-500">About</a>
                        </li>
                        <li>
                            <a href="#" class="block py-2 px-3 text-white hover:text-blue-500">Services</a>
                        </li>
                        <li>
                            <a href="#" class="block py-2 px-3 text-white hover:text-blue-500">Contact</a>
                        </li>
                    </ul>
                </div>
                
            </div>
        </nav>
    </header>
    <div class="grow">
            {% block content %}
            {% endblock content %}
    </div>
    <footer class="w-full h-56 bg-gray-700">
        <div class="max-w-screen-xl">

        </div>
    </footer>  
    {% block script %}
    {% endblock %}

    <script>
        document.body.addEventListener('configRequest.htmx', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
</body>  
</html>